Repository netgroup/kubernetes-playground, pull requests merged in 2020-04, with the labels that each got.

#125 fix and enhance cni (re)provisioning
  README.md
  Vagrantfile
  defaults.yaml
  scripts/linux/bootstrap-kubernetes-minion.sh
  scripts/linux/cleanup-k8s-and-cni.sh
Labels: bug, enhancement

#140 Don't install Docker compose
  ansible/roles/docker/defaults/main.yml
  ansible/roles/docker/tasks/main.yml
  ansible/roles/docker/vars/defaults.yml
Labels: enhancement

#139 Evict and delete nodes from the master to avoid warnings
  scripts/linux/cleanup-k8s-and-cni.sh
Labels: enhancement

#141 adding ext folder for exernal projects
  ext/.gitignore
  ext/README.md
Labels: enhancement

#138 Don't spawn a subshell when checking if /vagrant is mounted
  Vagrantfile
Labels: bug

#142 Upgrade vagrant to 2.2.7
  .travis.yml
Labels: enhancement

#145 Dynamically load environment vars from the CI environment and require Vagrant version
  Vagrantfile
Labels: enhancement

#148 Reorder build steps
  .travis.yml
Labels: enhancement

#155 Fix travis stage
  .travis.yml
Labels: bug

#150 Check if vagrant_provider is supported
  Vagrantfile
Labels: enhancement

#149 Move the sshd configuration script out of the Vagrantfile
  Vagrantfile
  scripts/linux/enable-ssh-password-authentication.sh
Labels: enhancement, technical debt

#151 Improve README flow and document defaults.yaml
  README.md
  defaults.yaml
Labels: enhancement

#152 Install Vagrant plugins
  README.md
  Vagrantfile
Labels: enhancement

#154 Don't add an additional disk to the base VM. Don't hardcode additional disk size
  Vagrantfile
  defaults.yaml
Labels: enhancement

#147 get interface name dynamically
  README.md
  Vagrantfile
  ansible/kubernetes.yml
  defaults.yaml
  scripts/linux/enable-ssh-password-authentication.sh
  scripts/linux/install-kubernetes.sh
Labels: enhancement, technical debt

#164 Improve the install-kubernetes.sh script
  scripts/linux/install-kubernetes.sh
Labels: enhancement

#168 Set go to 1.14.1
  .travis.yml
Labels: enhancement

#176 Set facts, debug info, remove ansible-provisioner
  README.md
  Vagrantfile
  ansible/kubernetes.yml
  ansible/templates/90-node-ip.conf.j2
  scripts/linux/install-kubernetes.sh
Labels: enhancement

#185 Run the Test-Kitchen suite on Travis
  .travis.yml
  kitchen.yml
  scripts/linux/ci/install-libvirt.sh
  scripts/linux/ci/install-vagrant-for-libvirt.sh
  scripts/linux/ci/install-vagrant-plugins.sh
  scripts/linux/ci/install-vagrant.sh
  test/integration/default/inspec/docker.rb
Labels: enhancement

#170 Use hostnames in inventory and variable files
  Vagrantfile
  ansible/kubernetes.yml
  ansible/templates/kubeadm-config.yaml.j2
Labels: enhancement

#191 stop all ansible tasks on a failure - close #188
  ansible/kubernetes.yml
Labels: enhancement

#182 Fix adding the additional disk and the loop on WSL by switching to triggers
  .travis.yml
  README.md
  Vagrantfile
  scripts/linux/ci/generate-env-for-travis.sh
  scripts/linux/enable-ssh-password-authentication.sh
Labels: bug

#173 Populate hosts file on guests
  .travis.yml
  Gemfile
  Vagrantfile
  ansible/kubernetes.yml
  scripts/linux/ci/install-libvirt.sh
  test/integration/default/inspec/kubernetes.rb
Labels: enhancement
